version: 1
formatters:
    simple:
        format: '%(asctime)s - %(levelname)s - %(module)s:: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: null # Path (Absolute or Relative) to where logs.txt should be saved, will be set to "./logs.txt" if not provided
loggers:
    raterLogger:
        level: INFO
        handlers: [console, file]
        propagate: no
root:
    level: INFO
    handlers: [console, file]