# Fast DEBUG mode
IS_DEBUG: false
NUM_DEBUG_ROWS: 40

# Reproducibility
SEED: 321

# Modeling & Training
MODEL_NAME: microsoft/deberta-v3-large
NUM_PURE_TARGETS: 7
NUM_INTERVAL: 2
NUM_TARGETS: 15
MAXLEN: 1024
TRUE_SEG_COEF: 0.6

EPOCHS: 4
EARLY_STOP_EPOCH: null
USE_AMP: true
SAVE_EACH: 0.2499
TRAIN_BATCH_SIZE: 4
TRAIN_NUM_WORKERS: 0
VAL_BATCH_SIZE: 16
VAL_NUM_WORKERS: 2
DEVICE: cpu # Will be automatically overrided if cuda is available
CLIP_GRAD_NORM: 2.0

N_DROPS: 5

# Loss & Optimizer
OPTIMIZER_LR: 3.0e-06
OPTIMIZER_WEIGHT_DECAY: 0.001
SCHEDULER_ETA_MIN: 1.0e-07

ALPHA_NER: 0.15
ALPHA_SEG: 0.75
ALPHA_EFF: 0.10

# Model Validation Strategy
FOLD_COL_NAME: fold
MAIN_METRIC_NAME: iov_v2_val
FOLDS:
    - 0

# Folders
DATA_ROOT: data/
TRAIN_ROOT: data/essays/ # full essay contents folder
TRAIN_CSV_PATH: data/train_v2.csv # training data csv file, in the correct format
FOLD_JSON_PATH: data/fold_dict.json # the folds, could be created using dataset.add_training_fold(...)
MODEL_ROOT: models/  # model checkpointing root folder
LOGS_TXT_PATH: logs.txt # the logging file, will contain log messages

# Efficient Data Usage Strategy
P_MASK_FREQ: 0.90
P_MASK_SIZE_LOW: 0.15
P_MASK_SIZE_HIGH: 0.35
P_RANDOM_START: 0.8
P_START_AT_SEQ_BEGINNING: 0.80
MIN_SEQ_LEN: 4096
FORCE_TRUNC_FREQ: 0.5
PYTORCH_CE_IGNORE_INDEX: -100
STRIDE_MAX_LEN_RATIO: 2

# Miscelaneous
# POSITION_DIV_FACTOR: 3

EFF2ID:
    Effective: 1
    Non-Effective: 0
ID2EFF:
    1: Effective
    0: Non-Effective
Discourse2ID:
    Claim: 1
    Concluding Statement: 2
    Counterclaim: 3
    Evidence: 4
    Lead: 5
    Position: 6
    Rebuttal: 7
ID2WEIGHTS:
    1: Claim
    2: Concluding Statement
    3: Counterclaim
    4: Evidence
    5: Lead
    6: Position
    7: Rebuttal
DISCOURSE2WEIGHTS:
    Claim: 0.127
    Concluding Statement: 0.075
    Counterclaim: 0.182
    Evidence: 0.102
    Lead: 0.079
    Position: 0.102
    Rebuttal: 0.259
ID2Weights:
    1: 0.2
    2: 0.8
CLASS_WEIGHTS:
    - 0.5763239860534668
    - 0.3956386148929596
    - 0.23364485800266266
    - 0.5669782161712646
    - 0.3177570402622223
    - 0.24610592424869537
    - 0.3177570402622223
    - 0.8068536520004272
    - 1.5825544595718384
    - 0.9345794320106506
    - 2.2679128646850586
    - 1.2710281610488892
    - 0.9844236969947815
    - 1.2710281610488892
    - 3.227414608001709
SEG_CLASS_WEIGHTS:
    - 1.0499999523162842
    - 0.75
    - 1.2000000476837158

CHECKPOINT_PATHS: # Will initialize model weights with these weights
    fold_0: models/old_fprize_db1l_06916.pth
    fold_1: models/old_fprize_db1l_06916.pth
    fold_2: models/old_fprize_db1l_06916.pth
    fold_3: models/old_fprize_db1l_06916.pth
    fold_4: models/old_fprize_db1l_06916.pth